"use client";

import React from "react";
import Link from "next/link";
import { Flag } from "lucide-react";
import { Card, SectionTitle } from "@/components/ui/misc";
import { Button } from "@/components/ui/Button";
import { Pill } from "@/components/ui/Badge";
import { useI18n } from "@/lib/i18n";
import { useToast } from "@/components/ui/Toast";
import { riskFlags } from "@/data/mock/admin";
import { getProviderById } from "@/data/mock/providers";

export default function AdminRiskPage() {
  const { lang, t } = useI18n();
  const { toast } = useToast();

  return (
    <div className="space-y-4">
      <SectionTitle
        title={t("Signaux de risque", "Risk flags")}
        subtitle={t(
          "Générés par les règles pilotes : litiges, écarts de réconciliation, vérifications expirées.",
          "Generated by pilot rules: disputes, reconciliation gaps, expired verifications."
        )}
      />
      <Card>
        <ul className="divide-y divide-line dark:divide-night-line">
          {riskFlags.map((f) => {
            const p = getProviderById(f.providerId);
            return (
              <li key={f.id} className="flex flex-wrap items-center gap-3 p-4">
                <Flag
                  className={
                    f.severity === "high"
                      ? "h-4 w-4 text-danger"
                      : f.severity === "medium"
                        ? "h-4 w-4 text-warn"
                        : "h-4 w-4 text-ink-faint"
                  }
                  aria-hidden
                />
                <div className="min-w-0 flex-1">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="text-[13px] font-bold">
                      {lang === "fr" ? f.labelFr : f.labelEn}
                    </span>
                    {f.severity === "high" && <Pill tone="red">{t("Élevé", "High")}</Pill>}
                    {f.severity === "medium" && <Pill tone="amber">{t("Moyen", "Medium")}</Pill>}
                    {f.severity === "low" && <Pill tone="neutral">{t("Faible", "Low")}</Pill>}
                  </div>
                  <p className="mt-0.5 text-xs text-ink-muted dark:text-[#8FA79C]">
                    {f.id} ·{" "}
                    {p && (
                      <Link href={`/providers/${p.slug}`} className="font-semibold text-brand-600 hover:underline dark:text-brand-300">
                        {p.name}
                      </Link>
                    )}{" "}
                    · {f.openedAt}
                  </p>
                </div>
                <div className="flex gap-2">
                  <Button
                    size="sm"
                    variant="secondary"
                    onClick={() => toast(t(`${f.id} : enquête ouverte (prototype)`, `${f.id}: investigation opened (prototype)`), "info")}
                  >
                    {t("Enquêter", "Investigate")}
                  </Button>
                  <Button
                    size="sm"
                    variant="ghost"
                    onClick={() => toast(t(`${f.id} : marqué traité`, `${f.id}: marked handled`))}
                  >
                    {t("Marquer traité", "Mark handled")}
                  </Button>
                </div>
              </li>
            );
          })}
        </ul>
      </Card>
    </div>
  );
}
